name: Docker Build

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t order-service:${{ github.run_number }} .